#!/usr/bin/env python3
"""
Add a food item to the SugarPace catalogue.

Updates:
  - resources/foods/foods.json
  - resources/drawables/drawables.xml
  - resources/drawables/brands/<picture>.png  (downloaded or copied, resized to 150x150)
  - source/DrawableRegistry.mc

Usage (local):
  python3 scripts/add_food.py \\
    --name "Energy Gel Cola" --brand "Decathlon" \\
    --subcategory GEL --portion 40 --carbs 26 --fat 0 --protein 0 \\
    --energy-kj 440 --image ./gel_cola.png [--gi 80]

Usage (from GitHub Actions, parsing an issue body):
  python3 scripts/add_food.py --from-issue-body <file>
"""
import argparse
import json
import os
import re
import sys
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

FOODS_JSON    = os.path.join(ROOT, "resources/foods/foods.json")
DRAWABLES_XML = os.path.join(ROOT, "resources/drawables/drawables.xml")
REGISTRY_MC   = os.path.join(ROOT, "source/DrawableRegistry.mc")
BRANDS_DIR    = os.path.join(ROOT, "resources/drawables/brands")

GI_BASELINES = {"GEL": 80, "JELLIES": 82, "BAR": 55, "OTHER": 65}


def slugify(text):
    return text.strip().lower().replace(" ", "_")


def estimate_gi(subcategory, fat_g, protein_g):
    baseline = GI_BASELINES.get(subcategory, 65)
    return max(20, round(baseline - 0.5 * fat_g - 0.3 * protein_g))


def make_picture(brand, name):
    return slugify(brand) + "_" + slugify(name)


def make_food_id(picture, portion_g):
    return f"{picture}_{int(portion_g)}"


def add_to_foods_json(entry):
    with open(FOODS_JSON) as f:
        foods = json.load(f)
    if any(e["id"] == entry["id"] for e in foods):
        print(f"SKIP: '{entry['id']}' already in foods.json")
        return
    foods.append(entry)
    foods.sort(key=lambda e: e["id"])
    with open(FOODS_JSON, "w") as f:
        json.dump(foods, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"  foods.json       ← {entry['id']}")


def add_to_drawables_xml(picture):
    with open(DRAWABLES_XML) as f:
        xml = f.read()
    if f'id="{picture}"' in xml:
        print(f"SKIP: '{picture}' already in drawables.xml")
        return
    line = f'    <bitmap id="{picture}" filename="brands/{picture}.png" />\n'
    # Insert before closing </drawables>
    xml = xml.replace("</drawables>", line + "</drawables>")
    with open(DRAWABLES_XML, "w") as f:
        f.write(xml)
    print(f"  drawables.xml    ← {picture}")


def add_to_registry_mc(picture):
    with open(REGISTRY_MC) as f:
        mc = f.read()
    if f'"{picture}"' in mc:
        print(f"SKIP: '{picture}' already in DrawableRegistry.mc")
        return
    # Find the last entry in the dictionary and insert after it
    # Pattern: last line matching `"..." => Rez.Drawables...,`
    last_entry = re.search(
        r'("[\w]+" *=> *Rez\.Drawables\.[\w]+,)\s*\n(\s*\})',
        mc,
        re.DOTALL
    )
    if not last_entry:
        print("ERROR: could not locate insertion point in DrawableRegistry.mc", file=sys.stderr)
        sys.exit(1)

    # Align with the longest existing key
    existing_keys = re.findall(r'"([\w]+)"\s*=>', mc)
    max_len = max(len(k) for k in existing_keys) if existing_keys else len(picture)
    pad = max(max_len, len(picture))

    new_line = f'                "{picture}"{"" :{pad - len(picture)}s}  => Rez.Drawables.{picture},'
    # Replace the closing brace to insert before it
    mc = mc.replace(
        last_entry.group(0),
        last_entry.group(1) + "\n" + new_line + "\n" + "            " + last_entry.group(2)
    )
    with open(REGISTRY_MC, "w") as f:
        f.write(mc)
    print(f"  DrawableRegistry ← {picture}")


def fetch_and_resize_image(source, dest_path):
    try:
        from PIL import Image
    except ImportError:
        print("ERROR: Pillow not installed. Run: pip install Pillow", file=sys.stderr)
        sys.exit(1)

    if source.startswith("http"):
        req = urllib.request.Request(source, headers={"User-Agent": "SugarPace-bot/1.0"})
        with urllib.request.urlopen(req) as r:
            data = r.read()
        import io
        img = Image.open(io.BytesIO(data)).convert("RGBA")
    else:
        img = Image.open(source).convert("RGBA")

    img = img.resize((150, 150), Image.LANCZOS)
    img.save(dest_path, "PNG")
    print(f"  brands/          ← {os.path.basename(dest_path)} (150×150)")


def _extract_image_url(raw):
    """Accept a raw URL or GitHub markdown image syntax ![...](url)."""
    if not raw:
        return raw
    # GitHub drag-and-drop gives markdown: ![filename](https://...)
    m = re.search(r'!\[.*?\]\((https?://\S+)\)', raw)
    if m:
        return m.group(1)
    # Or HTML: <img ... src="https://..." ...>
    m = re.search(r'<img\b[^>]*\bsrc="(https?://[^"]+)"', raw)
    if m:
        return m.group(1)
    return raw.strip()


def parse_issue_body(body_file):
    """Parse a GitHub issue body (markdown) generated by the add_food template."""
    with open(body_file) as f:
        text = f.read()

    def extract(label):
        m = re.search(rf"### {re.escape(label)}\s*\n+(.+?)(?:\n###|\Z)", text, re.DOTALL)
        return m.group(1).strip() if m else ""

    return {
        "name":       extract("Nom du produit"),
        "brand":      extract("Marque"),
        "subcategory":extract("Catégorie"),
        "portion_g":  float(extract("Portion (g)")),
        "carbs_g":    float(extract("Glucides pour la portion (g)")),
        "fat_g":      float(extract("Lipides pour la portion (g)")),
        "protein_g":  float(extract("Protéines pour la portion (g)")),
        "energy_kj":  int(extract("Énergie pour la portion (kJ)")),
        "image_url":  _extract_image_url(extract("Image du produit")),
    }


def run(name, brand, subcategory, portion_g, carbs_g, fat_g, protein_g,
        energy_kj, image_source):

    picture = make_picture(brand, name)
    food_id = make_food_id(picture, portion_g)
    gi_value = estimate_gi(subcategory, fat_g, protein_g)

    entry = {
        "id":         food_id,
        "name":       name.strip(),
        "brand":      brand.strip(),
        "picture":    picture,
        "subcategory":subcategory,
        "portion_g":  portion_g,
        "carbs_g":    carbs_g,
        "gi":         gi_value,
        "fat_g":      fat_g,
        "protein_g":  protein_g,
        "energy_kj":  energy_kj,
    }

    print(f"\nAjout de : {name} ({brand})  →  picture={picture}  gi={gi_value}")
    dest_png = os.path.join(BRANDS_DIR, f"{picture}.png")
    fetch_and_resize_image(image_source, dest_png)
    add_to_foods_json(entry)
    add_to_drawables_xml(picture)
    add_to_registry_mc(picture)
    print("Terminé. Lance validate_foods.py pour vérifier la cohérence.")


def main():
    parser = argparse.ArgumentParser(description="Add a food item to the SugarPace catalogue.")
    parser.add_argument("--from-issue-body", metavar="FILE",
                        help="Parse fields from a GitHub issue body file instead of CLI args")
    parser.add_argument("--name")
    parser.add_argument("--brand")
    parser.add_argument("--subcategory", choices=["GEL", "JELLIES", "BAR", "OTHER"])
    parser.add_argument("--portion", type=float)
    parser.add_argument("--carbs", type=float)
    parser.add_argument("--fat", type=float, default=0.0)
    parser.add_argument("--protein", type=float, default=0.0)
    parser.add_argument("--energy-kj", type=int)
    parser.add_argument("--image", help="Local path or URL to the product image")
    args = parser.parse_args()

    if args.from_issue_body:
        d = parse_issue_body(args.from_issue_body)
        # --brand / --name override issue body (provided by workflow from issue title)
        name  = args.name  if args.name  else d["name"]
        brand = args.brand if args.brand else d["brand"]
        run(name, brand, d["subcategory"],
            d["portion_g"], d["carbs_g"], d["fat_g"], d["protein_g"],
            d["energy_kj"], d["image_url"])
    else:
        missing = [f for f in ["name", "brand", "subcategory", "portion", "carbs", "energy_kj", "image"]
                   if getattr(args, f.replace("-", "_")) is None]
        if missing:
            parser.error(f"Champs requis manquants : {', '.join(missing)}")
        run(args.name, args.brand, args.subcategory,
            args.portion, args.carbs, args.fat, args.protein,
            args.energy_kj, args.image)


if __name__ == "__main__":
    main()
