/* GENERATED by video/narrate.py from script.json - do not edit */
window.TIMING = {
 "en": {
  "lang": "en",
  "voice": "Daniel",
  "estimate": false,
  "total": 116.801,
  "scenes": [
   {
    "id": "intro",
    "start": 0.0,
    "dur": 6,
    "lines": [
     {
      "t0": 0.8,
      "t1": 5.015,
      "text": "SugarPace. Your glucose and your fueling, on your Garmin Edge."
     }
    ]
   },
   {
    "id": "screen",
    "start": 6.0,
    "dur": 14,
    "lines": [
     {
      "t0": 6.6,
      "t1": 13.544,
      "text": "Your latest reading from your own Nightscout site, color-coded by range, with the trend arrow and the age of the reading."
     },
     {
      "t0": 13.994,
      "t1": 18.653,
      "text": "A chart of the last four hours, and the foods you carry, one tap away."
     }
    ]
   },
   {
    "id": "tap",
    "start": 20.0,
    "dur": 15.741,
    "lines": [
     {
      "t0": 20.6,
      "t1": 25.451,
      "text": "Tap a food tile to send a carb entry. It is secured by a one-time code."
     },
     {
      "t0": 25.901,
      "t1": 34.841,
      "text": "The tile shows the result: sending, sent, or failed with a short reason. Double taps are ignored, so an entry is never sent twice."
     }
    ]
   },
   {
    "id": "flow",
    "start": 35.741,
    "dur": 19.215,
    "lines": [
     {
      "t0": 36.341,
      "t1": 41.916,
      "text": "Behind the screen, your Edge uses your phone's connection to talk to your own Nightscout site."
     },
     {
      "t0": 42.366,
      "t1": 49.23,
      "text": "Glucose flows from your loop to Nightscout, then to your Edge. Carb entries flow back the other way, to your loop."
     },
     {
      "t0": 49.68,
      "t1": 54.055,
      "text": "SugarPace has no server of its own: nothing passes through the developer."
     }
    ]
   },
   {
    "id": "treat",
    "start": 54.955,
    "dur": 13.468,
    "lines": [
     {
      "t0": 55.555,
      "t1": 60.557,
      "text": "The Treatments screen lists your temporary profiles. Tap one to activate it."
     },
     {
      "t0": 61.007,
      "t1": 67.523,
      "text": "If the data gets old, the number turns grey after fifteen minutes, so an old value never looks current."
     }
    ]
   },
   {
    "id": "bolus",
    "start": 68.423,
    "dur": 21.851,
    "lines": [
     {
      "t0": 69.023,
      "t1": 74.669,
      "text": "Optionally, you can allow sending the bolus that your loop recommends. It is off by default."
     },
     {
      "t0": 75.119,
      "t1": 85.536,
      "text": "It needs two taps and a recommendation less than ten minutes old, and it never sends the same one twice. If something goes wrong, the screen tells you to check your loop first."
     },
     {
      "t0": 85.986,
      "t1": 89.374,
      "text": "This is real insulin: always confirm on your loop."
     }
    ]
   },
   {
    "id": "need",
    "start": 90.274,
    "dur": 12.857,
    "lines": [
     {
      "t0": 90.874,
      "t1": 102.231,
      "text": "You need a Nightscout site, a loop that accepts remote entries, and a touchscreen Edge: 840, 850, 1040 or 1050."
     }
    ]
   },
   {
    "id": "outro",
    "start": 103.131,
    "dur": 13.67,
    "lines": [
     {
      "t0": 103.631,
      "t1": 110.177,
      "text": "SugarPace is not a medical device. Always confirm values and decisions with your approved devices."
     },
     {
      "t0": 110.627,
      "t1": 115.901,
      "text": "Not affiliated with Garmin, Nightscout, or any loop app. Find it on GitHub."
     }
    ]
   }
  ]
 },
 "fr": {
  "lang": "fr",
  "voice": "Flo (Français (France))",
  "estimate": false,
  "total": 122.084,
  "scenes": [
   {
    "id": "intro",
    "start": 0.0,
    "dur": 6.404,
    "lines": [
     {
      "t0": 0.8,
      "t1": 5.504,
      "text": "SugarPace. Ta glycémie et ton ravitaillement, sur ton Garmin Edge."
     }
    ]
   },
   {
    "id": "screen",
    "start": 6.404,
    "dur": 14.14,
    "lines": [
     {
      "t0": 7.004,
      "t1": 14.351,
      "text": "Ta dernière mesure depuis ton propre site Nightscout, colorée selon la zone, avec la flèche de tendance et l'âge de la mesure."
     },
     {
      "t0": 14.801,
      "t1": 19.644,
      "text": "Un graphique des quatre dernières heures, et les aliments que tu emportes, à un tap."
     }
    ]
   },
   {
    "id": "tap",
    "start": 20.544,
    "dur": 17.666,
    "lines": [
     {
      "t0": 21.144,
      "t1": 27.172,
      "text": "Touche une vignette d'aliment pour envoyer une entrée de glucides. Elle est sécurisée par un code à usage unique."
     },
     {
      "t0": 27.622,
      "t1": 37.31,
      "text": "La vignette affiche le résultat : envoi, envoyé, ou échec avec une courte raison. Les doubles taps sont ignorés : une entrée n'est jamais envoyée deux fois."
     }
    ]
   },
   {
    "id": "flow",
    "start": 38.21,
    "dur": 21.542,
    "lines": [
     {
      "t0": 38.81,
      "t1": 45.029,
      "text": "Derrière l'écran, ton Edge utilise la connexion de ton téléphone pour parler à ton propre site Nightscout."
     },
     {
      "t0": 45.479,
      "t1": 53.594,
      "text": "La glycémie circule de ta boucle vers Nightscout, puis vers ton Edge. Les entrées de glucides font le chemin inverse, vers ta boucle."
     },
     {
      "t0": 54.044,
      "t1": 58.852,
      "text": "SugarPace n'a aucun serveur à lui : rien ne passe par le développeur."
     }
    ]
   },
   {
    "id": "treat",
    "start": 59.752,
    "dur": 13,
    "lines": [
     {
      "t0": 60.352,
      "t1": 64.918,
      "text": "L'écran Traitements liste tes profils temporaires. Touche-en un pour l'activer."
     },
     {
      "t0": 65.368,
      "t1": 71.818,
      "text": "Si la donnée vieillit, le chiffre devient gris après quinze minutes : une vieille valeur ne paraît jamais récente."
     }
    ]
   },
   {
    "id": "bolus",
    "start": 72.752,
    "dur": 21.913,
    "lines": [
     {
      "t0": 73.352,
      "t1": 79.421,
      "text": "En option, tu peux autoriser l'envoi du bolus recommandé par ta boucle. C'est désactivé par défaut."
     },
     {
      "t0": 79.871,
      "t1": 89.698,
      "text": "Il faut deux taps et une recommandation de moins de dix minutes, et la même n'est jamais envoyée deux fois. Si quelque chose se passe mal, l'écran te dit de vérifier ta boucle d'abord."
     },
     {
      "t0": 90.148,
      "t1": 93.765,
      "text": "C'est de l'insuline réelle : confirme toujours sur ta boucle."
     }
    ]
   },
   {
    "id": "need",
    "start": 94.665,
    "dur": 11.974,
    "lines": [
     {
      "t0": 95.265,
      "t1": 105.739,
      "text": "Il te faut un site Nightscout, une boucle qui accepte les entrées à distance, et un Edge tactile : 840, 850, 1040 ou 1050."
     }
    ]
   },
   {
    "id": "outro",
    "start": 106.639,
    "dur": 15.444,
    "lines": [
     {
      "t0": 107.139,
      "t1": 114.526,
      "text": "SugarPace n'est pas un dispositif médical. Vérifie toujours les valeurs et les décisions avec tes dispositifs approuvés."
     },
     {
      "t0": 114.976,
      "t1": 121.184,
      "text": "Sans affiliation avec Garmin, Nightscout ou une application de boucle. À retrouver sur GitHub."
     }
    ]
   }
  ]
 }
};
